<?php

use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{
    /** @var User */
    private $user;
    /** @var Mailer */
    private $mockedMailer;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $mailerMocked = $this->createMock(Mailer::class);
        $mailerMocked->method('sendEmail')->willReturn(true);
        $this->user = new User($mailerMocked);

    }

    function testEmptyName() {
        // Adding trim here because we are adding the space in getFullName.
        $this->assertEmpty($this->user->getFullName());
    }

    /**
     * Second way to writing php test cases.
     * @test
     */
    function check_empty_name() {
        // Adding trim here because we are adding the space in getFullName.
        $this->assertEmpty($this->user->getFullName());
    }

    function testGetFullNameAndReturnNothing() {
        $this->user->first_name = 'Zakir';
        $this->user->last_name = 'Mohammad';

        $expected = 'Zakir Mohammad';

        $this->assertEquals($expected, $this->user->getFullName());
    }



    public function testNotifyIsSent() {
        $this->user->email = "test@exmple.com";
        $this->assertTrue($this->user->notify('Hello'));
    }

}
