<?php

use PHPUnit\Framework\TestCase;
use PHPUnitPractice\User;

class UserTest extends TestCase
{
    private $user;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User();

    }

    function testGetFullNameAndReturnNothing() {
        $this->user->first_name = 'Zakir Pervez';
        $this->user->last_name = 'Mohammad';

        $expected = 'Zakir Pervez Mohammad';

        $this->assertEquals($expected, $this->user->getFullName());
    }

    function testEmptyName() {
        $user = new User();
        // Adding trim here because we are adding the space in getFullName.
        $this->assertEmpty($user->getFullName());
    }

    /**
     * Second way to writing php test cases.
     * @test
     */
    function check_empty_name() {
        $user = new User();
        // Adding trim here because we are adding the space in getFullName.
        $this->assertEmpty($user->getFullName());
    }

}
